<a href="https://colab.research.google.com/github/AnjuMau8418/ML_Learning/blob/main/MultiVariate_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Given the home prices in the file find out price of a home that has, 3000 sqr ft area, 3 bedrooms, 40 year old and
2500 sqr ft area, 4 bedrooms, 5 year old

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [11]:
df = pd.read_csv("HomePrice.csv")
df

Area  bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Data Pre-Processing

In [12]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [20]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

Area  bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Linear Regression Model with Multiple Independent Values


In [14]:
reg = linear_model.LinearRegression()
reg.fit(df[['Area','bedrooms','Age']], df.Price)

LinearRegression()

In [15]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [16]:
reg.intercept_

383724.9999999998

In [25]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [27]:
137.25*3000 + -26025. *3 +  -6825. *40 + 383724.9999999998

444399.9999999998

In [28]:
reg.predict([[2500,4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [29]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [30]:
reg.intercept_

383724.9999999998

In [31]:
2500*137.25 +  -26025.*4 + 5* -6825. + 383724.9999999998

588624.9999999998